############################################################
#
# See http://www.appveyor.com/docs/appveyor-yml for many more options
#
# Credit for a lot of this file goes to RamblingCookieMonster:
# https://github.com/RamblingCookieMonster/PSSQLite/blob/master/appveyor.yml
#
############################################################

# This tells AppVeyor that we need WMF 5 and PowerShell 5.0
os: WMF 5

environment:
    ModuleName: $(APPVEYOR_PROJECT_NAME)
    Tags: 'JIRA'
    LicenseUri: 'https://github.com/AtlassianPS/JiraPS/blob/master/LICENSE'
    ProjectUri: 'https://github.com/AtlassianPS/JiraPS/'

    # To encrypt a value in AppVeyor, go to the Account menu and choose "Encrypt data"
    PSGalleryAPIKey:
        secure: 5WCRuuF+sk5Mjnt5cL6uJw4cMU2QzDNE8uBXOw2hXSujE93zxRcROS3ZM1w85ui3

version: 2.1.0.{build}

# Only build commits to these branches
branches:
    only:
        - master
        - dev

# Don't rebuild when I tag a release on GitHub
skip_tags: true

skip_commits:
    message: /readme*/
    files:
        - .github/
        - .vscode/
        - assets/
        - docs/
        - Tools/

install:
    - cmd: git config --global core.autocrlf true
    - cmd: it config --global user.name "Oliver Lipkau"
    - cmd: it config --global user.email "oliver@lipkau.net"
    - cmd: git add .
    - cmd: git commit -m "Fix LFCR"
    - cmd: git push
    - cmd: npm install -g markdown-spellcheck
    # - ps: Get-PackageProvider -Name NuGet -ForceBootstrap | Out-Null
    # - ps: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
    # - ps: Install-Module BuildHelpers, InvokeBuild
    - ps: |
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force | Out-Null
        Install-Module InvokeBuild -RequiredVersion 3.2.1 -Scope CurrentUser -Force | Out-Null
        Install-Module BuildHelpers -Scope CurrentUser -Force | Out-Null

before_build:
    - ps: Invoke-Build -Task ShowDebug

test_script:
    # - cmd: mdspell '**/*.md' '!**/node_modules/**/*.md' --ignore-numbers --ignore-acronyms --report
    - ps: Invoke-Build -Task Test

build_script:
    - ps: Invoke-Build -Task Build

deploy_script:
    - ps: Invoke-Build -Task Deploy

notifications:
    - provider: Slack
      incoming_webhook: https://hooks.slack.com/services/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

# on_finish:
    # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
