environment:
    PSGalleryAPIKey:
        secure: Ezd2JjB6rbNZOiJmcek2bZSSdXB34fjoC6JXdXcICf6KZGoBOIRZAG9KfHAYiMa7
        # Must be updated to use contact@AtlassianPS.net user
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

version: 2.5.{build}

# Don't rebuild when I tag a release on GitHub
skip_tags: true

# Ignore testing a commit if only the readme changed
# Or if I include "skip-tests" in the commit message
skip_commits:
    message: /skip\-tests/
    files:
        - .github/
        - .vscode/
        - README.md
        - .gitattributes
        - .gitignore
        - .env*

# PRs, by definition, don't change anything and therefore should not increment the version
# To be fair, this is not important, and is really just AppVeyor enabling my pedantry
pull_requests:
  do_not_increment_build_number: true

init:
    - git config --global core.autocrlf true
    - git config --global credential.helper store
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
    - git config --global user.email "support@atlassianps.org"
    - git config --global user.name "AtlassianPS automation"

install:
    - powershell -File "./Tools/setup.ps1"

before_build:
    - ps: Invoke-Build -Task ShowDebug

build_script:
    - ps: Invoke-Build -Task Build

test_script:
    - ps: Invoke-Build -Task Test

before_deploy:
    - ps: Invoke-Build -Task Deploy

deploy:
    provider: GitHub
    release: v$(appveyor_build_version)
    description: ''
    auth_token:
        secure: ekVji7s19g/3zxpVQMX9gG1CldaXdOudCdY8a057AwcK5HyKZC0lFBE1Ou9iwBpu
    # artifact: /Release/JiraPS.zip
    draft: false
    prerelease: false
    on:
        branch: master                 # release from master branch only
        appveyor_repo_tag: false        # deploy on tag push only

# on_failure:
    # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
